; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32_board_deploy

[env:esp32_board_deploy]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.flash_size = 16MB
;debug_tool = esp-prog      ; comment out with ';' to use the default debug tool (USB-UART bridge)
;upload_protocol = esp-prog ; comment out with ';' to use the default debug tool (USB-UART bridge)
build_type = debug      ;build in debug mode instead of release mode
build_flags =
    -DPLATFORM_ESP32
    -Iinclude

[env:localhost_test]
platform = native
test_build_src = false
build_type = debug
build_unflags = -std=gnu++98
build_flags =
    -std=gnu++11
    -D UNITY_INT_WIDTH=32
    -D UNITY_FLOAT_TYPE=float_t
    -D unitTesting
    -Iinclude
    -Itest
    -lgcov
    --coverage
    -fprofile-abs-path
    -DPLATFORM_LOCALHOST
    -g3
    -O0
