
#include "rtdb.h"

#define DIMH_TI_MS_DEF_DIMMING_TIME_U32 ((tU32) 1000)
#define DIMH_DEF_DIMMING_MIN_U32        ((tU32)    0)
#define DIMH_DEF_DIMMING_DEF_U32        ((tU32)  500)
#define DIMH_DEF_DIMMING_MAX_U32        ((tU32) 1000)

tU16S    rtdb_dimh_x_dimmerTrshld_aU16       [32]; ///< []    [DIMH_DEF_DIMMING_MIN_U32]  [DIMH_DEF_DIMMING_MIN_U32]         [DIMH_DEF_DIMMING_MAX_U32]   [Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF]
tU16S    rtdb_dimh_x_dimmerOn_aU16           [32]; ///< []    [DIMH_DEF_DIMMING_MIN_U32]  [DIMH_DEF_DIMMING_DEF_U32]         [DIMH_DEF_DIMMING_MAX_U32]   [Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer]
tU16S    rtdb_dimh_x_txDimmerVal_aU16        [32]; ///< []    [DIMH_DEF_DIMMING_MIN_U32]  [DIMH_DEF_DIMMING_MIN_U32]         [DIMH_DEF_DIMMING_MAX_U32]   [Dimmer value in 0.1 prcnt]
tU32S    rtdb_dimh_ti_ms_txDimmerTime_aU32   [32]; ///< [ms]  [0]                         [DIMH_TI_MS_DEF_DIMMING_TIME_U32]  []                           [Dimming time in ms for both on and off]
tBS      rtdb_dimh_s_txDimmerRdyFlag_aB      [32]; ///< []    [0]                         [0]                                [1]                          [Dimmer data ready flag. Set by DIMH, cleared by CANM]

void dimh_rtdb_init()
{
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[0], RTDB_DIMH_X_DIMMERON_AU16_0, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[1], RTDB_DIMH_X_DIMMERON_AU16_1, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[2], RTDB_DIMH_X_DIMMERON_AU16_2, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[3], RTDB_DIMH_X_DIMMERON_AU16_3, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[4], RTDB_DIMH_X_DIMMERON_AU16_4, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[5], RTDB_DIMH_X_DIMMERON_AU16_5, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[6], RTDB_DIMH_X_DIMMERON_AU16_6, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[7], RTDB_DIMH_X_DIMMERON_AU16_7, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[8], RTDB_DIMH_X_DIMMERON_AU16_8, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[9], RTDB_DIMH_X_DIMMERON_AU16_9, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[10], RTDB_DIMH_X_DIMMERON_AU16_10, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[11], RTDB_DIMH_X_DIMMERON_AU16_11, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[12], RTDB_DIMH_X_DIMMERON_AU16_12, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[13], RTDB_DIMH_X_DIMMERON_AU16_13, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[14], RTDB_DIMH_X_DIMMERON_AU16_14, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[15], RTDB_DIMH_X_DIMMERON_AU16_15, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[16], RTDB_DIMH_X_DIMMERON_AU16_16, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[17], RTDB_DIMH_X_DIMMERON_AU16_17, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[18], RTDB_DIMH_X_DIMMERON_AU16_18, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[19], RTDB_DIMH_X_DIMMERON_AU16_19, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[20], RTDB_DIMH_X_DIMMERON_AU16_20, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[21], RTDB_DIMH_X_DIMMERON_AU16_21, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[22], RTDB_DIMH_X_DIMMERON_AU16_22, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[23], RTDB_DIMH_X_DIMMERON_AU16_23, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[24], RTDB_DIMH_X_DIMMERON_AU16_24, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[25], RTDB_DIMH_X_DIMMERON_AU16_25, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[26], RTDB_DIMH_X_DIMMERON_AU16_26, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[27], RTDB_DIMH_X_DIMMERON_AU16_27, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[28], RTDB_DIMH_X_DIMMERON_AU16_28, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[29], RTDB_DIMH_X_DIMMERON_AU16_29, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[30], RTDB_DIMH_X_DIMMERON_AU16_30, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerOn_aU16[31], RTDB_DIMH_X_DIMMERON_AU16_31, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_DEF_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[0], RTDB_DIMH_X_DIMMERTRSHLD_AU16_0, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[1], RTDB_DIMH_X_DIMMERTRSHLD_AU16_1, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[2], RTDB_DIMH_X_DIMMERTRSHLD_AU16_2, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[3], RTDB_DIMH_X_DIMMERTRSHLD_AU16_3, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[4], RTDB_DIMH_X_DIMMERTRSHLD_AU16_4, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[5], RTDB_DIMH_X_DIMMERTRSHLD_AU16_5, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[6], RTDB_DIMH_X_DIMMERTRSHLD_AU16_6, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[7], RTDB_DIMH_X_DIMMERTRSHLD_AU16_7, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[8], RTDB_DIMH_X_DIMMERTRSHLD_AU16_8, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[9], RTDB_DIMH_X_DIMMERTRSHLD_AU16_9, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[10], RTDB_DIMH_X_DIMMERTRSHLD_AU16_10, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[11], RTDB_DIMH_X_DIMMERTRSHLD_AU16_11, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[12], RTDB_DIMH_X_DIMMERTRSHLD_AU16_12, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[13], RTDB_DIMH_X_DIMMERTRSHLD_AU16_13, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[14], RTDB_DIMH_X_DIMMERTRSHLD_AU16_14, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[15], RTDB_DIMH_X_DIMMERTRSHLD_AU16_15, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[16], RTDB_DIMH_X_DIMMERTRSHLD_AU16_16, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[17], RTDB_DIMH_X_DIMMERTRSHLD_AU16_17, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[18], RTDB_DIMH_X_DIMMERTRSHLD_AU16_18, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[19], RTDB_DIMH_X_DIMMERTRSHLD_AU16_19, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[20], RTDB_DIMH_X_DIMMERTRSHLD_AU16_20, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[21], RTDB_DIMH_X_DIMMERTRSHLD_AU16_21, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[22], RTDB_DIMH_X_DIMMERTRSHLD_AU16_22, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[23], RTDB_DIMH_X_DIMMERTRSHLD_AU16_23, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[24], RTDB_DIMH_X_DIMMERTRSHLD_AU16_24, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[25], RTDB_DIMH_X_DIMMERTRSHLD_AU16_25, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[26], RTDB_DIMH_X_DIMMERTRSHLD_AU16_26, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[27], RTDB_DIMH_X_DIMMERTRSHLD_AU16_27, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[28], RTDB_DIMH_X_DIMMERTRSHLD_AU16_28, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[29], RTDB_DIMH_X_DIMMERTRSHLD_AU16_29, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[30], RTDB_DIMH_X_DIMMERTRSHLD_AU16_30, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_dimmerTrshld_aU16[31], RTDB_DIMH_X_DIMMERTRSHLD_AU16_31, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[0], RTDB_DIMH_X_TXDIMMERVAL_AU16_0, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[1], RTDB_DIMH_X_TXDIMMERVAL_AU16_1, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[2], RTDB_DIMH_X_TXDIMMERVAL_AU16_2, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[3], RTDB_DIMH_X_TXDIMMERVAL_AU16_3, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[4], RTDB_DIMH_X_TXDIMMERVAL_AU16_4, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[5], RTDB_DIMH_X_TXDIMMERVAL_AU16_5, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[6], RTDB_DIMH_X_TXDIMMERVAL_AU16_6, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[7], RTDB_DIMH_X_TXDIMMERVAL_AU16_7, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[8], RTDB_DIMH_X_TXDIMMERVAL_AU16_8, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[9], RTDB_DIMH_X_TXDIMMERVAL_AU16_9, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[10], RTDB_DIMH_X_TXDIMMERVAL_AU16_10, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[11], RTDB_DIMH_X_TXDIMMERVAL_AU16_11, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[12], RTDB_DIMH_X_TXDIMMERVAL_AU16_12, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[13], RTDB_DIMH_X_TXDIMMERVAL_AU16_13, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[14], RTDB_DIMH_X_TXDIMMERVAL_AU16_14, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[15], RTDB_DIMH_X_TXDIMMERVAL_AU16_15, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[16], RTDB_DIMH_X_TXDIMMERVAL_AU16_16, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[17], RTDB_DIMH_X_TXDIMMERVAL_AU16_17, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[18], RTDB_DIMH_X_TXDIMMERVAL_AU16_18, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[19], RTDB_DIMH_X_TXDIMMERVAL_AU16_19, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[20], RTDB_DIMH_X_TXDIMMERVAL_AU16_20, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[21], RTDB_DIMH_X_TXDIMMERVAL_AU16_21, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[22], RTDB_DIMH_X_TXDIMMERVAL_AU16_22, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[23], RTDB_DIMH_X_TXDIMMERVAL_AU16_23, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[24], RTDB_DIMH_X_TXDIMMERVAL_AU16_24, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[25], RTDB_DIMH_X_TXDIMMERVAL_AU16_25, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[26], RTDB_DIMH_X_TXDIMMERVAL_AU16_26, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[27], RTDB_DIMH_X_TXDIMMERVAL_AU16_27, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[28], RTDB_DIMH_X_TXDIMMERVAL_AU16_28, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[29], RTDB_DIMH_X_TXDIMMERVAL_AU16_29, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[30], RTDB_DIMH_X_TXDIMMERVAL_AU16_30, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU16S(&rtdb_dimh_x_txDimmerVal_aU16[31], RTDB_DIMH_X_TXDIMMERVAL_AU16_31, VAR_UNIT_NONE, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MIN_U32, DIMH_DEF_DIMMING_MAX_U32, "Dimmer value in 0.1 prcnt");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[0], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_0, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[1], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_1, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[2], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_2, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[3], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_3, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[4], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_4, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[5], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_5, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[6], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_6, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[7], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_7, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[8], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_8, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[9], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_9, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[10], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_10, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[11], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_11, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[12], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_12, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[13], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_13, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[14], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_14, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[15], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_15, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[16], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_16, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[17], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_17, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[18], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_18, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[19], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_19, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[20], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_20, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[21], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_21, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[22], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_22, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[23], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_23, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[24], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_24, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[25], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_25, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[26], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_26, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[27], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_27, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[28], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_28, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[29], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_29, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[30], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_30, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tU32S(&rtdb_dimh_ti_ms_txDimmerTime_aU32[31], RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_31, VAR_UNIT_ms, 0, DIMH_TI_MS_DEF_DIMMING_TIME_U32, TU32_MAX, "Dimming time in ms for both on and off");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[0], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_0, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[1], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_1, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[2], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_2, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[3], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_3, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[4], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_4, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[5], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_5, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[6], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_6, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[7], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_7, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[8], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_8, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[9], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_9, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[10], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_10, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[11], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_11, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[12], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_12, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[13], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_13, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[14], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_14, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[15], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_15, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[16], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_16, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[17], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_17, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[18], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_18, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[19], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_19, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[20], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_20, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[21], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_21, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[22], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_22, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[23], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_23, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[24], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_24, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[25], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_25, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[26], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_26, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[27], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_27, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[28], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_28, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[29], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_29, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[30], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_30, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
    rtdb_assign_tBS(&rtdb_dimh_s_txDimmerRdyFlag_aB[31], RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_31, VAR_UNIT_NONE, 0, 0, 1, "Dimmer data ready flag. Set by DIMH, cleared by CANM");
}