
#include "rtdb.h"

tBS      rtdb_canm_s_rxRelayInvertReq_aB   [128];
tU16S    rtdb_canm_x_rxActDimmVal_aU16     [32];
tBS      rtdb_canm_s_txGpioStates_aB       [32];
tBS      rtdb_canm_s_txRelayStates_aB      [128];

void canm_rtdb_init(void)
{
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[0], RTDB_CANM_S_RXRELAYINVERTREQ_AB_0, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[1], RTDB_CANM_S_RXRELAYINVERTREQ_AB_1, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[2], RTDB_CANM_S_RXRELAYINVERTREQ_AB_2, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[3], RTDB_CANM_S_RXRELAYINVERTREQ_AB_3, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[4], RTDB_CANM_S_RXRELAYINVERTREQ_AB_4, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[5], RTDB_CANM_S_RXRELAYINVERTREQ_AB_5, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[6], RTDB_CANM_S_RXRELAYINVERTREQ_AB_6, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[7], RTDB_CANM_S_RXRELAYINVERTREQ_AB_7, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[8], RTDB_CANM_S_RXRELAYINVERTREQ_AB_8, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[9], RTDB_CANM_S_RXRELAYINVERTREQ_AB_9, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[10], RTDB_CANM_S_RXRELAYINVERTREQ_AB_10, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[11], RTDB_CANM_S_RXRELAYINVERTREQ_AB_11, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[12], RTDB_CANM_S_RXRELAYINVERTREQ_AB_12, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[13], RTDB_CANM_S_RXRELAYINVERTREQ_AB_13, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[14], RTDB_CANM_S_RXRELAYINVERTREQ_AB_14, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[15], RTDB_CANM_S_RXRELAYINVERTREQ_AB_15, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[16], RTDB_CANM_S_RXRELAYINVERTREQ_AB_16, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[17], RTDB_CANM_S_RXRELAYINVERTREQ_AB_17, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[18], RTDB_CANM_S_RXRELAYINVERTREQ_AB_18, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[19], RTDB_CANM_S_RXRELAYINVERTREQ_AB_19, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[20], RTDB_CANM_S_RXRELAYINVERTREQ_AB_20, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[21], RTDB_CANM_S_RXRELAYINVERTREQ_AB_21, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[22], RTDB_CANM_S_RXRELAYINVERTREQ_AB_22, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[23], RTDB_CANM_S_RXRELAYINVERTREQ_AB_23, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[24], RTDB_CANM_S_RXRELAYINVERTREQ_AB_24, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[25], RTDB_CANM_S_RXRELAYINVERTREQ_AB_25, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[26], RTDB_CANM_S_RXRELAYINVERTREQ_AB_26, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[27], RTDB_CANM_S_RXRELAYINVERTREQ_AB_27, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[28], RTDB_CANM_S_RXRELAYINVERTREQ_AB_28, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[29], RTDB_CANM_S_RXRELAYINVERTREQ_AB_29, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[30], RTDB_CANM_S_RXRELAYINVERTREQ_AB_30, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[31], RTDB_CANM_S_RXRELAYINVERTREQ_AB_31, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[32], RTDB_CANM_S_RXRELAYINVERTREQ_AB_32, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[33], RTDB_CANM_S_RXRELAYINVERTREQ_AB_33, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[34], RTDB_CANM_S_RXRELAYINVERTREQ_AB_34, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[35], RTDB_CANM_S_RXRELAYINVERTREQ_AB_35, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[36], RTDB_CANM_S_RXRELAYINVERTREQ_AB_36, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[37], RTDB_CANM_S_RXRELAYINVERTREQ_AB_37, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[38], RTDB_CANM_S_RXRELAYINVERTREQ_AB_38, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[39], RTDB_CANM_S_RXRELAYINVERTREQ_AB_39, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[40], RTDB_CANM_S_RXRELAYINVERTREQ_AB_40, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[41], RTDB_CANM_S_RXRELAYINVERTREQ_AB_41, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[42], RTDB_CANM_S_RXRELAYINVERTREQ_AB_42, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[43], RTDB_CANM_S_RXRELAYINVERTREQ_AB_43, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[44], RTDB_CANM_S_RXRELAYINVERTREQ_AB_44, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[45], RTDB_CANM_S_RXRELAYINVERTREQ_AB_45, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[46], RTDB_CANM_S_RXRELAYINVERTREQ_AB_46, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[47], RTDB_CANM_S_RXRELAYINVERTREQ_AB_47, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[48], RTDB_CANM_S_RXRELAYINVERTREQ_AB_48, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[49], RTDB_CANM_S_RXRELAYINVERTREQ_AB_49, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[50], RTDB_CANM_S_RXRELAYINVERTREQ_AB_50, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[51], RTDB_CANM_S_RXRELAYINVERTREQ_AB_51, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[52], RTDB_CANM_S_RXRELAYINVERTREQ_AB_52, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[53], RTDB_CANM_S_RXRELAYINVERTREQ_AB_53, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[54], RTDB_CANM_S_RXRELAYINVERTREQ_AB_54, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[55], RTDB_CANM_S_RXRELAYINVERTREQ_AB_55, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[56], RTDB_CANM_S_RXRELAYINVERTREQ_AB_56, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[57], RTDB_CANM_S_RXRELAYINVERTREQ_AB_57, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[58], RTDB_CANM_S_RXRELAYINVERTREQ_AB_58, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[59], RTDB_CANM_S_RXRELAYINVERTREQ_AB_59, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[60], RTDB_CANM_S_RXRELAYINVERTREQ_AB_60, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[61], RTDB_CANM_S_RXRELAYINVERTREQ_AB_61, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[62], RTDB_CANM_S_RXRELAYINVERTREQ_AB_62, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[63], RTDB_CANM_S_RXRELAYINVERTREQ_AB_63, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[64], RTDB_CANM_S_RXRELAYINVERTREQ_AB_64, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[65], RTDB_CANM_S_RXRELAYINVERTREQ_AB_65, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[66], RTDB_CANM_S_RXRELAYINVERTREQ_AB_66, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[67], RTDB_CANM_S_RXRELAYINVERTREQ_AB_67, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[68], RTDB_CANM_S_RXRELAYINVERTREQ_AB_68, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[69], RTDB_CANM_S_RXRELAYINVERTREQ_AB_69, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[70], RTDB_CANM_S_RXRELAYINVERTREQ_AB_70, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[71], RTDB_CANM_S_RXRELAYINVERTREQ_AB_71, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[72], RTDB_CANM_S_RXRELAYINVERTREQ_AB_72, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[73], RTDB_CANM_S_RXRELAYINVERTREQ_AB_73, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[74], RTDB_CANM_S_RXRELAYINVERTREQ_AB_74, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[75], RTDB_CANM_S_RXRELAYINVERTREQ_AB_75, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[76], RTDB_CANM_S_RXRELAYINVERTREQ_AB_76, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[77], RTDB_CANM_S_RXRELAYINVERTREQ_AB_77, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[78], RTDB_CANM_S_RXRELAYINVERTREQ_AB_78, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[79], RTDB_CANM_S_RXRELAYINVERTREQ_AB_79, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[80], RTDB_CANM_S_RXRELAYINVERTREQ_AB_80, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[81], RTDB_CANM_S_RXRELAYINVERTREQ_AB_81, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[82], RTDB_CANM_S_RXRELAYINVERTREQ_AB_82, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[83], RTDB_CANM_S_RXRELAYINVERTREQ_AB_83, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[84], RTDB_CANM_S_RXRELAYINVERTREQ_AB_84, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[85], RTDB_CANM_S_RXRELAYINVERTREQ_AB_85, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[86], RTDB_CANM_S_RXRELAYINVERTREQ_AB_86, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[87], RTDB_CANM_S_RXRELAYINVERTREQ_AB_87, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[88], RTDB_CANM_S_RXRELAYINVERTREQ_AB_88, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[89], RTDB_CANM_S_RXRELAYINVERTREQ_AB_89, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[90], RTDB_CANM_S_RXRELAYINVERTREQ_AB_90, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[91], RTDB_CANM_S_RXRELAYINVERTREQ_AB_91, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[92], RTDB_CANM_S_RXRELAYINVERTREQ_AB_92, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[93], RTDB_CANM_S_RXRELAYINVERTREQ_AB_93, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[94], RTDB_CANM_S_RXRELAYINVERTREQ_AB_94, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[95], RTDB_CANM_S_RXRELAYINVERTREQ_AB_95, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[96], RTDB_CANM_S_RXRELAYINVERTREQ_AB_96, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[97], RTDB_CANM_S_RXRELAYINVERTREQ_AB_97, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[98], RTDB_CANM_S_RXRELAYINVERTREQ_AB_98, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[99], RTDB_CANM_S_RXRELAYINVERTREQ_AB_99, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[100], RTDB_CANM_S_RXRELAYINVERTREQ_AB_100, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[101], RTDB_CANM_S_RXRELAYINVERTREQ_AB_101, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[102], RTDB_CANM_S_RXRELAYINVERTREQ_AB_102, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[103], RTDB_CANM_S_RXRELAYINVERTREQ_AB_103, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[104], RTDB_CANM_S_RXRELAYINVERTREQ_AB_104, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[105], RTDB_CANM_S_RXRELAYINVERTREQ_AB_105, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[106], RTDB_CANM_S_RXRELAYINVERTREQ_AB_106, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[107], RTDB_CANM_S_RXRELAYINVERTREQ_AB_107, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[108], RTDB_CANM_S_RXRELAYINVERTREQ_AB_108, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[109], RTDB_CANM_S_RXRELAYINVERTREQ_AB_109, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[110], RTDB_CANM_S_RXRELAYINVERTREQ_AB_110, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[111], RTDB_CANM_S_RXRELAYINVERTREQ_AB_111, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[112], RTDB_CANM_S_RXRELAYINVERTREQ_AB_112, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[113], RTDB_CANM_S_RXRELAYINVERTREQ_AB_113, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[114], RTDB_CANM_S_RXRELAYINVERTREQ_AB_114, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[115], RTDB_CANM_S_RXRELAYINVERTREQ_AB_115, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[116], RTDB_CANM_S_RXRELAYINVERTREQ_AB_116, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[117], RTDB_CANM_S_RXRELAYINVERTREQ_AB_117, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[118], RTDB_CANM_S_RXRELAYINVERTREQ_AB_118, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[119], RTDB_CANM_S_RXRELAYINVERTREQ_AB_119, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[120], RTDB_CANM_S_RXRELAYINVERTREQ_AB_120, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[121], RTDB_CANM_S_RXRELAYINVERTREQ_AB_121, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[122], RTDB_CANM_S_RXRELAYINVERTREQ_AB_122, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[123], RTDB_CANM_S_RXRELAYINVERTREQ_AB_123, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[124], RTDB_CANM_S_RXRELAYINVERTREQ_AB_124, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[125], RTDB_CANM_S_RXRELAYINVERTREQ_AB_125, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[126], RTDB_CANM_S_RXRELAYINVERTREQ_AB_126, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_rxRelayInvertReq_aB[127], RTDB_CANM_S_RXRELAYINVERTREQ_AB_127, VAR_UNIT_NONE, 0, 0, 1, "Relay invert requests");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[0], RTDB_CANM_S_TXGPIOSTATES_AB_0, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[1], RTDB_CANM_S_TXGPIOSTATES_AB_1, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[2], RTDB_CANM_S_TXGPIOSTATES_AB_2, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[3], RTDB_CANM_S_TXGPIOSTATES_AB_3, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[4], RTDB_CANM_S_TXGPIOSTATES_AB_4, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[5], RTDB_CANM_S_TXGPIOSTATES_AB_5, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[6], RTDB_CANM_S_TXGPIOSTATES_AB_6, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[7], RTDB_CANM_S_TXGPIOSTATES_AB_7, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[8], RTDB_CANM_S_TXGPIOSTATES_AB_8, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[9], RTDB_CANM_S_TXGPIOSTATES_AB_9, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[10], RTDB_CANM_S_TXGPIOSTATES_AB_10, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[11], RTDB_CANM_S_TXGPIOSTATES_AB_11, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[12], RTDB_CANM_S_TXGPIOSTATES_AB_12, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[13], RTDB_CANM_S_TXGPIOSTATES_AB_13, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[14], RTDB_CANM_S_TXGPIOSTATES_AB_14, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[15], RTDB_CANM_S_TXGPIOSTATES_AB_15, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[16], RTDB_CANM_S_TXGPIOSTATES_AB_16, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[17], RTDB_CANM_S_TXGPIOSTATES_AB_17, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[18], RTDB_CANM_S_TXGPIOSTATES_AB_18, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[19], RTDB_CANM_S_TXGPIOSTATES_AB_19, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[20], RTDB_CANM_S_TXGPIOSTATES_AB_20, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[21], RTDB_CANM_S_TXGPIOSTATES_AB_21, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[22], RTDB_CANM_S_TXGPIOSTATES_AB_22, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[23], RTDB_CANM_S_TXGPIOSTATES_AB_23, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[24], RTDB_CANM_S_TXGPIOSTATES_AB_24, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[25], RTDB_CANM_S_TXGPIOSTATES_AB_25, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[26], RTDB_CANM_S_TXGPIOSTATES_AB_26, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[27], RTDB_CANM_S_TXGPIOSTATES_AB_27, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[28], RTDB_CANM_S_TXGPIOSTATES_AB_28, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[29], RTDB_CANM_S_TXGPIOSTATES_AB_29, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[30], RTDB_CANM_S_TXGPIOSTATES_AB_30, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txGpioStates_aB[31], RTDB_CANM_S_TXGPIOSTATES_AB_31, VAR_UNIT_NONE, 0, 0, 1, "State of GPIOs");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[0], RTDB_CANM_S_TXRELAYSTATES_AB_0, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[1], RTDB_CANM_S_TXRELAYSTATES_AB_1, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[2], RTDB_CANM_S_TXRELAYSTATES_AB_2, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[3], RTDB_CANM_S_TXRELAYSTATES_AB_3, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[4], RTDB_CANM_S_TXRELAYSTATES_AB_4, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[5], RTDB_CANM_S_TXRELAYSTATES_AB_5, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[6], RTDB_CANM_S_TXRELAYSTATES_AB_6, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[7], RTDB_CANM_S_TXRELAYSTATES_AB_7, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[8], RTDB_CANM_S_TXRELAYSTATES_AB_8, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[9], RTDB_CANM_S_TXRELAYSTATES_AB_9, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[10], RTDB_CANM_S_TXRELAYSTATES_AB_10, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[11], RTDB_CANM_S_TXRELAYSTATES_AB_11, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[12], RTDB_CANM_S_TXRELAYSTATES_AB_12, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[13], RTDB_CANM_S_TXRELAYSTATES_AB_13, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[14], RTDB_CANM_S_TXRELAYSTATES_AB_14, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[15], RTDB_CANM_S_TXRELAYSTATES_AB_15, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[16], RTDB_CANM_S_TXRELAYSTATES_AB_16, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[17], RTDB_CANM_S_TXRELAYSTATES_AB_17, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[18], RTDB_CANM_S_TXRELAYSTATES_AB_18, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[19], RTDB_CANM_S_TXRELAYSTATES_AB_19, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[20], RTDB_CANM_S_TXRELAYSTATES_AB_20, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[21], RTDB_CANM_S_TXRELAYSTATES_AB_21, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[22], RTDB_CANM_S_TXRELAYSTATES_AB_22, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[23], RTDB_CANM_S_TXRELAYSTATES_AB_23, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[24], RTDB_CANM_S_TXRELAYSTATES_AB_24, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[25], RTDB_CANM_S_TXRELAYSTATES_AB_25, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[26], RTDB_CANM_S_TXRELAYSTATES_AB_26, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[27], RTDB_CANM_S_TXRELAYSTATES_AB_27, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[28], RTDB_CANM_S_TXRELAYSTATES_AB_28, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[29], RTDB_CANM_S_TXRELAYSTATES_AB_29, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[30], RTDB_CANM_S_TXRELAYSTATES_AB_30, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[31], RTDB_CANM_S_TXRELAYSTATES_AB_31, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[32], RTDB_CANM_S_TXRELAYSTATES_AB_32, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[33], RTDB_CANM_S_TXRELAYSTATES_AB_33, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[34], RTDB_CANM_S_TXRELAYSTATES_AB_34, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[35], RTDB_CANM_S_TXRELAYSTATES_AB_35, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[36], RTDB_CANM_S_TXRELAYSTATES_AB_36, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[37], RTDB_CANM_S_TXRELAYSTATES_AB_37, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[38], RTDB_CANM_S_TXRELAYSTATES_AB_38, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[39], RTDB_CANM_S_TXRELAYSTATES_AB_39, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[40], RTDB_CANM_S_TXRELAYSTATES_AB_40, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[41], RTDB_CANM_S_TXRELAYSTATES_AB_41, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[42], RTDB_CANM_S_TXRELAYSTATES_AB_42, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[43], RTDB_CANM_S_TXRELAYSTATES_AB_43, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[44], RTDB_CANM_S_TXRELAYSTATES_AB_44, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[45], RTDB_CANM_S_TXRELAYSTATES_AB_45, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[46], RTDB_CANM_S_TXRELAYSTATES_AB_46, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[47], RTDB_CANM_S_TXRELAYSTATES_AB_47, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[48], RTDB_CANM_S_TXRELAYSTATES_AB_48, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[49], RTDB_CANM_S_TXRELAYSTATES_AB_49, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[50], RTDB_CANM_S_TXRELAYSTATES_AB_50, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[51], RTDB_CANM_S_TXRELAYSTATES_AB_51, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[52], RTDB_CANM_S_TXRELAYSTATES_AB_52, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[53], RTDB_CANM_S_TXRELAYSTATES_AB_53, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[54], RTDB_CANM_S_TXRELAYSTATES_AB_54, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[55], RTDB_CANM_S_TXRELAYSTATES_AB_55, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[56], RTDB_CANM_S_TXRELAYSTATES_AB_56, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[57], RTDB_CANM_S_TXRELAYSTATES_AB_57, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[58], RTDB_CANM_S_TXRELAYSTATES_AB_58, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[59], RTDB_CANM_S_TXRELAYSTATES_AB_59, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[60], RTDB_CANM_S_TXRELAYSTATES_AB_60, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[61], RTDB_CANM_S_TXRELAYSTATES_AB_61, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[62], RTDB_CANM_S_TXRELAYSTATES_AB_62, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[63], RTDB_CANM_S_TXRELAYSTATES_AB_63, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[64], RTDB_CANM_S_TXRELAYSTATES_AB_64, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[65], RTDB_CANM_S_TXRELAYSTATES_AB_65, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[66], RTDB_CANM_S_TXRELAYSTATES_AB_66, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[67], RTDB_CANM_S_TXRELAYSTATES_AB_67, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[68], RTDB_CANM_S_TXRELAYSTATES_AB_68, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[69], RTDB_CANM_S_TXRELAYSTATES_AB_69, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[70], RTDB_CANM_S_TXRELAYSTATES_AB_70, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[71], RTDB_CANM_S_TXRELAYSTATES_AB_71, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[72], RTDB_CANM_S_TXRELAYSTATES_AB_72, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[73], RTDB_CANM_S_TXRELAYSTATES_AB_73, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[74], RTDB_CANM_S_TXRELAYSTATES_AB_74, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[75], RTDB_CANM_S_TXRELAYSTATES_AB_75, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[76], RTDB_CANM_S_TXRELAYSTATES_AB_76, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[77], RTDB_CANM_S_TXRELAYSTATES_AB_77, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[78], RTDB_CANM_S_TXRELAYSTATES_AB_78, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[79], RTDB_CANM_S_TXRELAYSTATES_AB_79, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[80], RTDB_CANM_S_TXRELAYSTATES_AB_80, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[81], RTDB_CANM_S_TXRELAYSTATES_AB_81, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[82], RTDB_CANM_S_TXRELAYSTATES_AB_82, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[83], RTDB_CANM_S_TXRELAYSTATES_AB_83, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[84], RTDB_CANM_S_TXRELAYSTATES_AB_84, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[85], RTDB_CANM_S_TXRELAYSTATES_AB_85, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[86], RTDB_CANM_S_TXRELAYSTATES_AB_86, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[87], RTDB_CANM_S_TXRELAYSTATES_AB_87, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[88], RTDB_CANM_S_TXRELAYSTATES_AB_88, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[89], RTDB_CANM_S_TXRELAYSTATES_AB_89, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[90], RTDB_CANM_S_TXRELAYSTATES_AB_90, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[91], RTDB_CANM_S_TXRELAYSTATES_AB_91, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[92], RTDB_CANM_S_TXRELAYSTATES_AB_92, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[93], RTDB_CANM_S_TXRELAYSTATES_AB_93, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[94], RTDB_CANM_S_TXRELAYSTATES_AB_94, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[95], RTDB_CANM_S_TXRELAYSTATES_AB_95, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[96], RTDB_CANM_S_TXRELAYSTATES_AB_96, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[97], RTDB_CANM_S_TXRELAYSTATES_AB_97, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[98], RTDB_CANM_S_TXRELAYSTATES_AB_98, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[99], RTDB_CANM_S_TXRELAYSTATES_AB_99, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[100], RTDB_CANM_S_TXRELAYSTATES_AB_100, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[101], RTDB_CANM_S_TXRELAYSTATES_AB_101, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[102], RTDB_CANM_S_TXRELAYSTATES_AB_102, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[103], RTDB_CANM_S_TXRELAYSTATES_AB_103, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[104], RTDB_CANM_S_TXRELAYSTATES_AB_104, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[105], RTDB_CANM_S_TXRELAYSTATES_AB_105, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[106], RTDB_CANM_S_TXRELAYSTATES_AB_106, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[107], RTDB_CANM_S_TXRELAYSTATES_AB_107, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[108], RTDB_CANM_S_TXRELAYSTATES_AB_108, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[109], RTDB_CANM_S_TXRELAYSTATES_AB_109, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[110], RTDB_CANM_S_TXRELAYSTATES_AB_110, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[111], RTDB_CANM_S_TXRELAYSTATES_AB_111, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[112], RTDB_CANM_S_TXRELAYSTATES_AB_112, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[113], RTDB_CANM_S_TXRELAYSTATES_AB_113, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[114], RTDB_CANM_S_TXRELAYSTATES_AB_114, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[115], RTDB_CANM_S_TXRELAYSTATES_AB_115, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[116], RTDB_CANM_S_TXRELAYSTATES_AB_116, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[117], RTDB_CANM_S_TXRELAYSTATES_AB_117, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[118], RTDB_CANM_S_TXRELAYSTATES_AB_118, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[119], RTDB_CANM_S_TXRELAYSTATES_AB_119, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[120], RTDB_CANM_S_TXRELAYSTATES_AB_120, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[121], RTDB_CANM_S_TXRELAYSTATES_AB_121, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[122], RTDB_CANM_S_TXRELAYSTATES_AB_122, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[123], RTDB_CANM_S_TXRELAYSTATES_AB_123, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[124], RTDB_CANM_S_TXRELAYSTATES_AB_124, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[125], RTDB_CANM_S_TXRELAYSTATES_AB_125, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[126], RTDB_CANM_S_TXRELAYSTATES_AB_126, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tBS(&rtdb_canm_s_txRelayStates_aB[127], RTDB_CANM_S_TXRELAYSTATES_AB_127, VAR_UNIT_NONE, 0, 0, 1, "State of relays");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[0], RTDB_CANM_X_RXACTDIMMVAL_AU16_0, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[1], RTDB_CANM_X_RXACTDIMMVAL_AU16_1, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[2], RTDB_CANM_X_RXACTDIMMVAL_AU16_2, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[3], RTDB_CANM_X_RXACTDIMMVAL_AU16_3, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[4], RTDB_CANM_X_RXACTDIMMVAL_AU16_4, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[5], RTDB_CANM_X_RXACTDIMMVAL_AU16_5, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[6], RTDB_CANM_X_RXACTDIMMVAL_AU16_6, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[7], RTDB_CANM_X_RXACTDIMMVAL_AU16_7, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[8], RTDB_CANM_X_RXACTDIMMVAL_AU16_8, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[9], RTDB_CANM_X_RXACTDIMMVAL_AU16_9, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[10], RTDB_CANM_X_RXACTDIMMVAL_AU16_10, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[11], RTDB_CANM_X_RXACTDIMMVAL_AU16_11, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[12], RTDB_CANM_X_RXACTDIMMVAL_AU16_12, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[13], RTDB_CANM_X_RXACTDIMMVAL_AU16_13, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[14], RTDB_CANM_X_RXACTDIMMVAL_AU16_14, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[15], RTDB_CANM_X_RXACTDIMMVAL_AU16_15, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[16], RTDB_CANM_X_RXACTDIMMVAL_AU16_16, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[17], RTDB_CANM_X_RXACTDIMMVAL_AU16_17, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[18], RTDB_CANM_X_RXACTDIMMVAL_AU16_18, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[19], RTDB_CANM_X_RXACTDIMMVAL_AU16_19, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[20], RTDB_CANM_X_RXACTDIMMVAL_AU16_20, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[21], RTDB_CANM_X_RXACTDIMMVAL_AU16_21, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[22], RTDB_CANM_X_RXACTDIMMVAL_AU16_22, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[23], RTDB_CANM_X_RXACTDIMMVAL_AU16_23, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[24], RTDB_CANM_X_RXACTDIMMVAL_AU16_24, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[25], RTDB_CANM_X_RXACTDIMMVAL_AU16_25, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[26], RTDB_CANM_X_RXACTDIMMVAL_AU16_26, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[27], RTDB_CANM_X_RXACTDIMMVAL_AU16_27, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[28], RTDB_CANM_X_RXACTDIMMVAL_AU16_28, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[29], RTDB_CANM_X_RXACTDIMMVAL_AU16_29, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[30], RTDB_CANM_X_RXACTDIMMVAL_AU16_30, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
    rtdb_assign_tU16S(&rtdb_canm_x_rxActDimmVal_aU16[31], RTDB_CANM_X_RXACTDIMMVAL_AU16_31, VAR_UNIT_NONE, 0, 0, 1000, "Actual dimmer value in 0.1 prcnt as received on CAN");
}