/*
 * This file was autogenerated by RTDB Generator script
 * Date of generation: 13 April 2025 at 14:12:48
 * To modify this file run the RTDB Generator script again
 * Include this header file only in the corresponding module .cpp file to avoid multiple definitions
 */

#ifndef DIOM_RTDB_H
#define DIOM_RTDB_H

#include "rtdb.h"
#include "diom_rtdb_vars.h"

void diom_rtdb_init()
{
    rtdb_assign_tU32S(&diom_ti_cooldownPeriod_U32, DIOM_TI_COOLDOWNPERIOD_U32, VAR_UNIT_us, DIOM_TI_US_MIN_COOLDOWN_TIME, 5000, DIOM_TI_US_MAX_COOLDOWN_TIME, "Time in us for how long the signal has to settle before change to it can be registered again.");
    rtdb_assign_tU32S(&diom_ti_inputStates_U32, DIOM_TI_INPUTSTATES_U32, VAR_UNIT_NONE, 0, 0, 0xFFFFFFFF, "States of the inputs as 32 bit mask");
    rtdb_assign_tU32S(&diom_ti_taskTime_U32, DIOM_TI_TASKTIME_U32, VAR_UNIT_us, DIOM_TI_US_MIN_TASK_TIME_U32, 100, DIOM_TI_US_MAX_TASK_TIME_U32, "Time in us between task execution");
}
#endif
