/*
 * This file was autogenerated by RTDB Generator script
 * Date of generation: 12 April 2025 at 09:58:02
 * To modify this file run the RTDB Generator script again
 */

#ifndef DIOM_RTDB_H
#define DIOM_RTDB_H

#include "rtdb.h"
#include "diom_rtdb_vars.h"

void diom_rtdb_init()
{
    rtdb_assign_tU32S(&diom_ti_cooldownPeriod_U32, DIOM_TI_COOLDOWNPERIOD_U32, VAR_UNIT_us, 0, 2000, 10000, "Time in us for how long the signal has to settle before change to it can be registered again.");
    rtdb_assign_tU32S(&diom_ti_taskTime_U32, DIOM_TI_TASKTIME_U32, VAR_UNIT_us, 0, 500, 1000, "Time in us between task execution");
}
#endif
