/*
 * This file was autogenerated by RTDB Generator script
 * Date of generation: 17 April 2025 at 15:08:26
 * To modify this file run the RTDB Generator script again
 * Include this header file only in the corresponding module .cpp file to avoid multiple definitions
 */

#ifndef MBCM_RTDB_H
#define MBCM_RTDB_H

#include "rtdb.h"
#include "mbcm_rtdb_vars.h"

void mbcm_rtdb_init()
{
    rtdb_assign_tU32S(&rtdb_mbcm_ti_us_taskPeriodPwrMeter_U32, RTDB_MBCM_TI_US_TASKPERIODPWRMETER_U32, VAR_UNIT_us, MBCM_TI_US_MIN_TASK_TIME_PWRMETER_U32, MBCM_TI_US_DEF_TASK_TIME_PWRMETER_U32, MBCM_TI_US_MAX_TASK_TIME_PWRMETER_U32, "Time in us between Modbus messages for Power Meter modules");
    rtdb_assign_tU32S(&rtdb_mbcm_ti_us_taskPeriodRelay_U32, RTDB_MBCM_TI_US_TASKPERIODRELAY_U32, VAR_UNIT_us, MBCM_TI_US_MIN_TASK_TIME_RELAY_U32, MBCM_TI_US_DEF_TASK_TIME_RELAY_U32, MBCM_TI_US_MAX_TASK_TIME_RELAY_U32, "Time in us between Modbus messages for Relay modules");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[0], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_0, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[1], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_1, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[2], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_2, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[3], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_3, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[4], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_4, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[5], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_5, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[6], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_6, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[7], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_7, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[8], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_8, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[9], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_9, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[10], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_10, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[11], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_11, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[12], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_12, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[13], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_13, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[14], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_14, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_actualRelayStates_aU8[15], RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_15, VAR_UNIT_NONE, 0, 0, 0xFF, "Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[0], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_0, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[1], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_1, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[2], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_2, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[3], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_3, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[4], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_4, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[5], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_5, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[6], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_6, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[7], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_7, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[8], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_8, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[9], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_9, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[10], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_10, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[11], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_11, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[12], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_12, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[13], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_13, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[14], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_14, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
    rtdb_assign_tU8S(&rtdb_mbcm_x_desiredRelayStates_aU8[15], RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_15, VAR_UNIT_NONE, 0, 0, 0xFF, "Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays");
}
#endif
