/*
 * This file was autogenerated by RTDB Generator script
 * Date of generation: 13 April 2025 at 14:12:48
 * To modify this file run the RTDB Generator script again
 * Include this header file only in the corresponding module .cpp file to avoid multiple definitions
 */

#ifndef MBCM_RTDB_H
#define MBCM_RTDB_H

#include "rtdb.h"
#include "mbcm_rtdb_vars.h"

void mbcm_rtdb_init()
{
    rtdb_assign_tU32S(&mbcm_ti_us_taskPeriodPwrMeter_U32, MBCM_TI_US_TASKPERIODPWRMETER_U32, VAR_UNIT_us, MBCM_TI_US_MIN_TASK_TIME_PWRMETER_U32, MBCM_TI_US_DEF_TASK_TIME_PWRMETER_U32, MBCM_TI_US_MAX_TASK_TIME_PWRMETER_U32, "Time in us between Modbus messages for Power Meter modules");
    rtdb_assign_tU32S(&mbcm_ti_us_taskPeriodRelay_U32, MBCM_TI_US_TASKPERIODRELAY_U32, VAR_UNIT_us, MBCM_TI_US_MIN_TASK_TIME_RELAY_U32, MBCM_TI_US_DEF_TASK_TIME_RELAY_U32, MBCM_TI_US_MAX_TASK_TIME_RELAY_U32, "Time in us between Modbus messages for Relay modules");
    rtdb_assign_tU32S(&mbcm_x_desiredRelayStates_U32, MBCM_X_DESIREDRELAYSTATES_U32, VAR_UNIT_NONE, 0, 0, 0xFFFFFFFF, "Desired relay states as 32 bit mask");
}
#endif
