/*
 * This file was autogenerated by RTDB Generator script
 * Date of generation: 17 April 2025 at 15:08:26
 * To modify this file run the RTDB Generator script again
 * Include this header file only in the corresponding module .cpp file to avoid multiple definitions
 */

#ifndef RTDB_VARS_H
#define RTDB_VARS_H

#include<limits.h>
#include<stdint.h>
#include<float.h>

#include<vars.h>

// Variable units lookup table and enum
typedef enum
{
    VAR_UNIT_NONE = 0,
    VAR_UNIT_us,
    VAR_UNIT_MAX_NUM
} unitEnumT;

// tU8S
typedef enum
{
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_0 = 0,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_1 = 1,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_2 = 2,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_3 = 3,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_4 = 4,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_5 = 5,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_6 = 6,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_7 = 7,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_8 = 8,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_9 = 9,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_10 = 10,    // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_11 = 11,    // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_12 = 12,    // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_13 = 13,    // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_14 = 14,    // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_15 = 15,    // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_0 = 16,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_1 = 17,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_2 = 18,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_3 = 19,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_4 = 20,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_5 = 21,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_6 = 22,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_7 = 23,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_8 = 24,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_9 = 25,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_10 = 26,   // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_11 = 27,   // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_12 = 28,   // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_13 = 29,   // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_14 = 30,   // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_15 = 31,   // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    NUM_OF_tU8S = 32
} tU8SEnumT;

// tU16S
typedef enum
{
    NUM_OF_tU16S = 0
} tU16SEnumT;

// tU32S
typedef enum
{
    RTDB_DIOM_TI_US_COOLDOWNPERIOD_U32 = 0,       // Time in us for how long the signal has to settle before change to it can be registered again.
    RTDB_DIOM_TI_US_TASKTIME_U32 = 1,             // Time in us between task execution
    RTDB_DIOM_X_INPUTSTATES_U32 = 2,              // States of the inputs as 32 bit mask
    RTDB_MBCM_TI_US_TASKPERIODPWRMETER_U32 = 3,   // Time in us between Modbus messages for Power Meter modules
    RTDB_MBCM_TI_US_TASKPERIODRELAY_U32 = 4,      // Time in us between Modbus messages for Relay modules
    NUM_OF_tU32S = 5
} tU32SEnumT;

// tS8S
typedef enum
{
    NUM_OF_tS8S = 0
} tS8SEnumT;

// tS16S
typedef enum
{
    NUM_OF_tS16S = 0
} tS16SEnumT;

// tS32S
typedef enum
{
    NUM_OF_tS32S = 0
} tS32SEnumT;

// tES
typedef enum
{
    NUM_OF_tES = 0
} tESEnumT;

// tBS
typedef enum
{
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_0 = 0,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_1 = 1,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_2 = 2,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_3 = 3,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_4 = 4,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_5 = 5,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_6 = 6,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_7 = 7,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_8 = 8,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_9 = 9,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_10 = 10,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_11 = 11,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_12 = 12,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_13 = 13,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_14 = 14,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_15 = 15,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_16 = 16,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_17 = 17,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_18 = 18,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_19 = 19,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_20 = 20,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_21 = 21,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_22 = 22,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_23 = 23,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_24 = 24,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_25 = 25,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_26 = 26,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_27 = 27,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_28 = 28,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_29 = 29,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_30 = 30,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_31 = 31,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_32 = 32,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_33 = 33,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_34 = 34,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_35 = 35,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_36 = 36,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_37 = 37,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_38 = 38,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_39 = 39,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_40 = 40,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_41 = 41,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_42 = 42,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_43 = 43,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_44 = 44,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_45 = 45,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_46 = 46,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_47 = 47,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_48 = 48,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_49 = 49,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_50 = 50,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_51 = 51,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_52 = 52,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_53 = 53,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_54 = 54,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_55 = 55,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_56 = 56,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_57 = 57,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_58 = 58,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_59 = 59,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_60 = 60,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_61 = 61,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_62 = 62,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_63 = 63,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_64 = 64,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_65 = 65,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_66 = 66,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_67 = 67,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_68 = 68,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_69 = 69,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_70 = 70,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_71 = 71,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_72 = 72,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_73 = 73,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_74 = 74,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_75 = 75,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_76 = 76,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_77 = 77,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_78 = 78,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_79 = 79,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_80 = 80,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_81 = 81,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_82 = 82,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_83 = 83,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_84 = 84,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_85 = 85,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_86 = 86,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_87 = 87,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_88 = 88,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_89 = 89,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_90 = 90,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_91 = 91,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_92 = 92,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_93 = 93,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_94 = 94,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_95 = 95,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_96 = 96,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_97 = 97,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_98 = 98,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_99 = 99,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_100 = 100,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_101 = 101,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_102 = 102,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_103 = 103,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_104 = 104,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_105 = 105,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_106 = 106,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_107 = 107,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_108 = 108,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_109 = 109,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_110 = 110,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_111 = 111,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_112 = 112,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_113 = 113,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_114 = 114,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_115 = 115,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_116 = 116,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_117 = 117,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_118 = 118,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_119 = 119,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_120 = 120,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_121 = 121,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_122 = 122,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_123 = 123,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_124 = 124,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_125 = 125,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_126 = 126,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_127 = 127,    // Relay invert requests
    RTDB_CANM_S_TXGPIOSTATES_AB_0 = 128,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_1 = 129,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_2 = 130,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_3 = 131,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_4 = 132,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_5 = 133,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_6 = 134,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_7 = 135,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_8 = 136,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_9 = 137,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_10 = 138,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_11 = 139,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_12 = 140,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_13 = 141,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_14 = 142,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_15 = 143,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_16 = 144,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_17 = 145,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_18 = 146,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_19 = 147,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_20 = 148,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_21 = 149,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_22 = 150,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_23 = 151,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_24 = 152,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_25 = 153,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_26 = 154,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_27 = 155,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_28 = 156,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_29 = 157,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_30 = 158,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_31 = 159,         // State of GPIOs
    RTDB_CANM_S_TXRELAYSTATES_AB_0 = 160,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_1 = 161,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_2 = 162,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_3 = 163,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_4 = 164,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_5 = 165,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_6 = 166,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_7 = 167,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_8 = 168,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_9 = 169,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_10 = 170,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_11 = 171,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_12 = 172,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_13 = 173,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_14 = 174,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_15 = 175,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_16 = 176,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_17 = 177,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_18 = 178,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_19 = 179,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_20 = 180,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_21 = 181,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_22 = 182,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_23 = 183,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_24 = 184,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_25 = 185,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_26 = 186,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_27 = 187,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_28 = 188,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_29 = 189,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_30 = 190,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_31 = 191,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_32 = 192,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_33 = 193,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_34 = 194,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_35 = 195,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_36 = 196,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_37 = 197,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_38 = 198,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_39 = 199,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_40 = 200,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_41 = 201,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_42 = 202,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_43 = 203,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_44 = 204,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_45 = 205,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_46 = 206,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_47 = 207,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_48 = 208,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_49 = 209,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_50 = 210,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_51 = 211,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_52 = 212,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_53 = 213,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_54 = 214,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_55 = 215,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_56 = 216,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_57 = 217,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_58 = 218,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_59 = 219,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_60 = 220,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_61 = 221,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_62 = 222,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_63 = 223,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_64 = 224,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_65 = 225,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_66 = 226,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_67 = 227,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_68 = 228,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_69 = 229,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_70 = 230,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_71 = 231,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_72 = 232,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_73 = 233,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_74 = 234,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_75 = 235,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_76 = 236,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_77 = 237,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_78 = 238,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_79 = 239,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_80 = 240,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_81 = 241,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_82 = 242,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_83 = 243,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_84 = 244,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_85 = 245,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_86 = 246,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_87 = 247,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_88 = 248,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_89 = 249,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_90 = 250,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_91 = 251,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_92 = 252,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_93 = 253,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_94 = 254,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_95 = 255,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_96 = 256,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_97 = 257,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_98 = 258,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_99 = 259,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_100 = 260,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_101 = 261,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_102 = 262,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_103 = 263,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_104 = 264,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_105 = 265,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_106 = 266,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_107 = 267,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_108 = 268,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_109 = 269,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_110 = 270,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_111 = 271,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_112 = 272,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_113 = 273,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_114 = 274,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_115 = 275,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_116 = 276,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_117 = 277,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_118 = 278,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_119 = 279,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_120 = 280,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_121 = 281,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_122 = 282,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_123 = 283,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_124 = 284,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_125 = 285,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_126 = 286,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_127 = 287,       // State of relays
    NUM_OF_tBS = 288
} tBSEnumT;

// tF32S
typedef enum
{
    NUM_OF_tF32S = 0
} tF32SEnumT;

typedef enum
{
    SIGNAL_ERROR = 0,           ///< Value unreliable, use default
    SIGNAL_CAN_TIMEOUT = 194,   ///< Timeout on CAN signal
    SIGNAL_OK = 255
} signalStateT;

typedef enum
{
    OBJECT_STANDARD = 0,    ///< Value is derived from program
    OBJECT_OVERRIDDEN = 1,  ///< Value is derived from external source
    OBJECT_NOT_INIT = 255,
} objectStatusT;

typedef struct
{
    tU32 crc32;                         ///< CRC of all object's variables
    signalStateT signalState : 8;       ///< state of the signal, i.e., its reliability
    objectStatusT objectStatus : 8;     ///< status of this object
    tU8 signalUnit;                     ///< unit of the signal, i.e., volt or RPM
    const char* signalCmnt;             ///< Signal comment
} rtdbT;

typedef struct
{
    rtdbT ss;
    tS8 tS8_val;
    tS8 tS8_min;
    tS8 tS8_def;
    tS8 tS8_max;
} tS8S;

typedef struct
{
    rtdbT ss;
    tS16 tS16_val;
    tS16 tS16_min;
    tS16 tS16_def;
    tS16 tS16_max;
} tS16S;

typedef struct
{
    rtdbT ss;
    tS32 tS32_val;
    tS32 tS32_min;
    tS32 tS32_def;
    tS32 tS32_max;
} tS32S;

typedef struct
{
    rtdbT ss;
    tU8 tU8_val;
    tU8 tU8_min;
    tU8 tU8_def;
    tU8 tU8_max;
} tU8S;

typedef struct
{
    rtdbT ss;
    tU16 tU16_val;
    tU16 tU16_min;
    tU16 tU16_def;
    tU16 tU16_max;
} tU16S;

typedef struct
{
    rtdbT ss;
    tU32 tU32_val;
    tU32 tU32_min;
    tU32 tU32_def;
    tU32 tU32_max;
} tU32S;

typedef struct
{
    rtdbT ss;
    tF32 tF32_val;
    tF32 tF32_min;
    tF32 tF32_def;
    tF32 tF32_max;
} tF32S;

typedef struct
{
    rtdbT ss;
    tU8 tB_val;
    tU8 tB_min;
    tU8 tB_def;
    tU8 tB_max;
} tBS;

typedef struct
{
    rtdbT ss;
    tU32 tE_val;
    tU32 tE_min;
    tU32 tE_def;
    tU32 tE_max;
} tES;

#endif
