/*
 * This file was autogenerated by RTDB Generator script
 * Date of generation: 28 April 2025 at 12:27:25
 * To modify this file run the RTDB Generator script again
 * Include this header file only in the corresponding module .cpp file to avoid multiple definitions
 */

#ifndef RTDB_VARS_H
#define RTDB_VARS_H

#include<limits.h>
#include<stdint.h>
#include<float.h>

#include<vars.h>

// Variable units lookup table and enum
typedef enum
{
    VAR_UNIT_NONE = 0,
    VAR_UNIT_ms,
    VAR_UNIT_us,
    VAR_UNIT_MAX_NUM
} unitEnumT;

// tU8S
typedef enum
{
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_0 = 0,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_1 = 1,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_2 = 2,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_3 = 3,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_4 = 4,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_5 = 5,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_6 = 6,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_7 = 7,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_8 = 8,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_9 = 9,      // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_10 = 10,    // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_11 = 11,    // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_12 = 12,    // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_13 = 13,    // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_14 = 14,    // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_ACTUALRELAYSTATES_AU8_15 = 15,    // Actual relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_0 = 16,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_1 = 17,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_2 = 18,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_3 = 19,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_4 = 20,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_5 = 21,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_6 = 22,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_7 = 23,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_8 = 24,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_9 = 25,    // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_10 = 26,   // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_11 = 27,   // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_12 = 28,   // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_13 = 29,   // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_14 = 30,   // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    RTDB_MBCM_X_DESIREDRELAYSTATES_AU8_15 = 31,   // Desired relay states as 8 bit mask, 1 for each relay module. Max 16 relay modules for a total of 128 relays
    NUM_OF_tU8S = 32
} tU8SEnumT;

// tU16S
typedef enum
{
    RTDB_CANM_X_RXACTDIMMVAL_AU16_0 = 0,          // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_1 = 1,          // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_2 = 2,          // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_3 = 3,          // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_4 = 4,          // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_5 = 5,          // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_6 = 6,          // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_7 = 7,          // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_8 = 8,          // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_9 = 9,          // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_10 = 10,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_11 = 11,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_12 = 12,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_13 = 13,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_14 = 14,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_15 = 15,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_16 = 16,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_17 = 17,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_18 = 18,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_19 = 19,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_20 = 20,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_21 = 21,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_22 = 22,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_23 = 23,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_24 = 24,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_25 = 25,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_26 = 26,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_27 = 27,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_28 = 28,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_29 = 29,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_30 = 30,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_CANM_X_RXACTDIMMVAL_AU16_31 = 31,        // Actual dimmer value in 0.1 prcnt as received on CAN
    RTDB_DIMH_X_DIMMERON_AU16_0 = 32,             // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_1 = 33,             // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_2 = 34,             // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_3 = 35,             // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_4 = 36,             // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_5 = 37,             // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_6 = 38,             // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_7 = 39,             // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_8 = 40,             // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_9 = 41,             // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_10 = 42,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_11 = 43,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_12 = 44,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_13 = 45,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_14 = 46,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_15 = 47,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_16 = 48,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_17 = 49,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_18 = 50,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_19 = 51,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_20 = 52,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_21 = 53,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_22 = 54,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_23 = 55,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_24 = 56,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_25 = 57,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_26 = 58,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_27 = 59,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_28 = 60,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_29 = 61,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_30 = 62,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERON_AU16_31 = 63,            // Dimmer ON value. When dimmer is set to ON this value is used to set the dimmer
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_0 = 64,         // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_1 = 65,         // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_2 = 66,         // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_3 = 67,         // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_4 = 68,         // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_5 = 69,         // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_6 = 70,         // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_7 = 71,         // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_8 = 72,         // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_9 = 73,         // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_10 = 74,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_11 = 75,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_12 = 76,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_13 = 77,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_14 = 78,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_15 = 79,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_16 = 80,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_17 = 81,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_18 = 82,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_19 = 83,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_20 = 84,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_21 = 85,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_22 = 86,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_23 = 87,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_24 = 88,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_25 = 89,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_26 = 90,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_27 = 91,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_28 = 92,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_29 = 93,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_30 = 94,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_DIMMERTRSHLD_AU16_31 = 95,        // Dimmer treshold. If actual value is below this treshold the dimmer is considered OFF
    RTDB_DIMH_X_TXDIMMERVAL_AU16_0 = 96,          // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_1 = 97,          // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_2 = 98,          // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_3 = 99,          // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_4 = 100,         // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_5 = 101,         // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_6 = 102,         // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_7 = 103,         // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_8 = 104,         // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_9 = 105,         // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_10 = 106,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_11 = 107,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_12 = 108,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_13 = 109,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_14 = 110,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_15 = 111,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_16 = 112,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_17 = 113,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_18 = 114,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_19 = 115,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_20 = 116,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_21 = 117,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_22 = 118,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_23 = 119,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_24 = 120,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_25 = 121,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_26 = 122,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_27 = 123,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_28 = 124,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_29 = 125,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_30 = 126,        // Dimmer value in 0.1 prcnt
    RTDB_DIMH_X_TXDIMMERVAL_AU16_31 = 127,        // Dimmer value in 0.1 prcnt
    NUM_OF_tU16S = 128
} tU16SEnumT;

// tU32S
typedef enum
{
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_0 = 0,      // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_1 = 1,      // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_2 = 2,      // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_3 = 3,      // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_4 = 4,      // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_5 = 5,      // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_6 = 6,      // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_7 = 7,      // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_8 = 8,      // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_9 = 9,      // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_10 = 10,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_11 = 11,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_12 = 12,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_13 = 13,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_14 = 14,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_15 = 15,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_16 = 16,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_17 = 17,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_18 = 18,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_19 = 19,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_20 = 20,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_21 = 21,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_22 = 22,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_23 = 23,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_24 = 24,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_25 = 25,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_26 = 26,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_27 = 27,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_28 = 28,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_29 = 29,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_30 = 30,    // Dimming time in ms for both on and off
    RTDB_DIMH_TI_MS_TXDIMMERTIME_AU32_31 = 31,    // Dimming time in ms for both on and off
    RTDB_DIOM_TI_US_COOLDOWNPERIOD_U32 = 32,      // Time in us for how long the signal has to settle before change to it can be registered again.
    RTDB_DIOM_TI_US_TASKTIME_U32 = 33,            // Time in us between task execution
    RTDB_DIOM_X_INPUTSTATES_U32 = 34,             // States of the inputs as 32 bit mask
    RTDB_MBCM_TI_US_TASKPERIODPWRMETER_U32 = 35,  // Time in us between Modbus messages for Power Meter modules
    RTDB_MBCM_TI_US_TASKPERIODRELAY_U32 = 36,     // Time in us between Modbus messages for Relay modules
    NUM_OF_tU32S = 37
} tU32SEnumT;

// tS8S
typedef enum
{
    NUM_OF_tS8S = 0
} tS8SEnumT;

// tS16S
typedef enum
{
    NUM_OF_tS16S = 0
} tS16SEnumT;

// tS32S
typedef enum
{
    NUM_OF_tS32S = 0
} tS32SEnumT;

// tES
typedef enum
{
    NUM_OF_tES = 0
} tESEnumT;

// tBS
typedef enum
{
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_0 = 0,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_1 = 1,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_2 = 2,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_3 = 3,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_4 = 4,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_5 = 5,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_6 = 6,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_7 = 7,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_8 = 8,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_9 = 9,        // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_10 = 10,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_11 = 11,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_12 = 12,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_13 = 13,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_14 = 14,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_15 = 15,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_16 = 16,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_17 = 17,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_18 = 18,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_19 = 19,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_20 = 20,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_21 = 21,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_22 = 22,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_23 = 23,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_24 = 24,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_25 = 25,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_26 = 26,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_27 = 27,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_28 = 28,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_29 = 29,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_30 = 30,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_31 = 31,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_32 = 32,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_33 = 33,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_34 = 34,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_35 = 35,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_36 = 36,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_37 = 37,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_38 = 38,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_39 = 39,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_40 = 40,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_41 = 41,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_42 = 42,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_43 = 43,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_44 = 44,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_45 = 45,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_46 = 46,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_47 = 47,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_48 = 48,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_49 = 49,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_50 = 50,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_51 = 51,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_52 = 52,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_53 = 53,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_54 = 54,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_55 = 55,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_56 = 56,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_57 = 57,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_58 = 58,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_59 = 59,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_60 = 60,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_61 = 61,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_62 = 62,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_63 = 63,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_64 = 64,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_65 = 65,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_66 = 66,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_67 = 67,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_68 = 68,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_69 = 69,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_70 = 70,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_71 = 71,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_72 = 72,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_73 = 73,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_74 = 74,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_75 = 75,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_76 = 76,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_77 = 77,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_78 = 78,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_79 = 79,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_80 = 80,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_81 = 81,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_82 = 82,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_83 = 83,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_84 = 84,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_85 = 85,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_86 = 86,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_87 = 87,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_88 = 88,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_89 = 89,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_90 = 90,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_91 = 91,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_92 = 92,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_93 = 93,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_94 = 94,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_95 = 95,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_96 = 96,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_97 = 97,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_98 = 98,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_99 = 99,      // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_100 = 100,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_101 = 101,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_102 = 102,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_103 = 103,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_104 = 104,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_105 = 105,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_106 = 106,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_107 = 107,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_108 = 108,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_109 = 109,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_110 = 110,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_111 = 111,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_112 = 112,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_113 = 113,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_114 = 114,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_115 = 115,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_116 = 116,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_117 = 117,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_118 = 118,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_119 = 119,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_120 = 120,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_121 = 121,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_122 = 122,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_123 = 123,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_124 = 124,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_125 = 125,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_126 = 126,    // Relay invert requests
    RTDB_CANM_S_RXRELAYINVERTREQ_AB_127 = 127,    // Relay invert requests
    RTDB_CANM_S_TXGPIOSTATES_AB_0 = 128,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_1 = 129,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_2 = 130,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_3 = 131,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_4 = 132,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_5 = 133,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_6 = 134,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_7 = 135,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_8 = 136,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_9 = 137,          // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_10 = 138,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_11 = 139,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_12 = 140,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_13 = 141,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_14 = 142,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_15 = 143,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_16 = 144,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_17 = 145,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_18 = 146,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_19 = 147,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_20 = 148,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_21 = 149,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_22 = 150,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_23 = 151,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_24 = 152,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_25 = 153,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_26 = 154,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_27 = 155,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_28 = 156,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_29 = 157,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_30 = 158,         // State of GPIOs
    RTDB_CANM_S_TXGPIOSTATES_AB_31 = 159,         // State of GPIOs
    RTDB_CANM_S_TXRELAYSTATES_AB_0 = 160,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_1 = 161,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_2 = 162,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_3 = 163,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_4 = 164,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_5 = 165,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_6 = 166,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_7 = 167,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_8 = 168,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_9 = 169,         // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_10 = 170,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_11 = 171,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_12 = 172,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_13 = 173,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_14 = 174,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_15 = 175,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_16 = 176,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_17 = 177,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_18 = 178,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_19 = 179,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_20 = 180,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_21 = 181,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_22 = 182,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_23 = 183,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_24 = 184,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_25 = 185,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_26 = 186,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_27 = 187,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_28 = 188,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_29 = 189,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_30 = 190,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_31 = 191,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_32 = 192,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_33 = 193,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_34 = 194,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_35 = 195,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_36 = 196,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_37 = 197,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_38 = 198,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_39 = 199,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_40 = 200,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_41 = 201,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_42 = 202,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_43 = 203,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_44 = 204,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_45 = 205,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_46 = 206,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_47 = 207,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_48 = 208,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_49 = 209,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_50 = 210,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_51 = 211,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_52 = 212,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_53 = 213,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_54 = 214,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_55 = 215,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_56 = 216,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_57 = 217,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_58 = 218,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_59 = 219,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_60 = 220,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_61 = 221,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_62 = 222,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_63 = 223,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_64 = 224,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_65 = 225,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_66 = 226,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_67 = 227,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_68 = 228,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_69 = 229,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_70 = 230,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_71 = 231,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_72 = 232,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_73 = 233,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_74 = 234,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_75 = 235,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_76 = 236,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_77 = 237,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_78 = 238,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_79 = 239,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_80 = 240,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_81 = 241,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_82 = 242,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_83 = 243,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_84 = 244,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_85 = 245,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_86 = 246,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_87 = 247,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_88 = 248,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_89 = 249,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_90 = 250,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_91 = 251,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_92 = 252,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_93 = 253,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_94 = 254,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_95 = 255,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_96 = 256,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_97 = 257,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_98 = 258,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_99 = 259,        // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_100 = 260,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_101 = 261,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_102 = 262,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_103 = 263,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_104 = 264,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_105 = 265,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_106 = 266,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_107 = 267,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_108 = 268,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_109 = 269,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_110 = 270,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_111 = 271,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_112 = 272,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_113 = 273,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_114 = 274,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_115 = 275,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_116 = 276,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_117 = 277,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_118 = 278,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_119 = 279,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_120 = 280,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_121 = 281,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_122 = 282,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_123 = 283,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_124 = 284,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_125 = 285,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_126 = 286,       // State of relays
    RTDB_CANM_S_TXRELAYSTATES_AB_127 = 287,       // State of relays
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_0 = 288,       // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_1 = 289,       // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_2 = 290,       // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_3 = 291,       // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_4 = 292,       // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_5 = 293,       // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_6 = 294,       // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_7 = 295,       // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_8 = 296,       // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_9 = 297,       // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_10 = 298,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_11 = 299,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_12 = 300,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_13 = 301,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_14 = 302,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_15 = 303,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_16 = 304,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_17 = 305,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_18 = 306,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_19 = 307,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_20 = 308,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_21 = 309,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_22 = 310,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_23 = 311,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_24 = 312,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_25 = 313,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_26 = 314,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_27 = 315,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_28 = 316,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_29 = 317,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_30 = 318,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    RTDB_DIMH_S_TXDIMMERRDYFLAG_AB_31 = 319,      // Dimmer data ready flag. Set by DIMH, cleared by CANM
    NUM_OF_tBS = 320
} tBSEnumT;

// tF32S
typedef enum
{
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_0 = 0,     // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_1 = 1,     // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_2 = 2,     // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_3 = 3,     // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_4 = 4,     // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_5 = 5,     // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_6 = 6,     // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_7 = 7,     // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_8 = 8,     // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_9 = 9,     // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_10 = 10,   // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_11 = 11,   // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_12 = 12,   // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_13 = 13,   // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_14 = 14,   // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_15 = 15,   // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_16 = 16,   // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_17 = 17,   // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_18 = 18,   // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_19 = 19,   // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_0_AF32_20 = 20,   // SDM120M readings as 32 bit float, for module 0
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_0 = 21,    // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_1 = 22,    // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_2 = 23,    // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_3 = 24,    // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_4 = 25,    // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_5 = 26,    // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_6 = 27,    // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_7 = 28,    // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_8 = 29,    // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_9 = 30,    // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_10 = 31,   // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_11 = 32,   // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_12 = 33,   // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_13 = 34,   // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_14 = 35,   // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_15 = 36,   // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_16 = 37,   // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_17 = 38,   // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_18 = 39,   // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_19 = 40,   // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_1_AF32_20 = 41,   // SDM120M readings as 32 bit float, for module 1
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_0 = 42,    // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_1 = 43,    // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_2 = 44,    // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_3 = 45,    // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_4 = 46,    // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_5 = 47,    // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_6 = 48,    // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_7 = 49,    // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_8 = 50,    // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_9 = 51,    // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_10 = 52,   // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_11 = 53,   // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_12 = 54,   // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_13 = 55,   // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_14 = 56,   // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_15 = 57,   // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_16 = 58,   // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_17 = 59,   // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_18 = 60,   // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_19 = 61,   // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_2_AF32_20 = 62,   // SDM120M readings as 32 bit float, for module 2
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_0 = 63,    // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_1 = 64,    // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_2 = 65,    // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_3 = 66,    // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_4 = 67,    // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_5 = 68,    // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_6 = 69,    // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_7 = 70,    // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_8 = 71,    // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_9 = 72,    // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_10 = 73,   // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_11 = 74,   // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_12 = 75,   // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_13 = 76,   // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_14 = 77,   // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_15 = 78,   // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_16 = 79,   // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_17 = 80,   // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_18 = 81,   // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_19 = 82,   // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_3_AF32_20 = 83,   // SDM120M readings as 32 bit float, for module 3
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_0 = 84,    // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_1 = 85,    // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_2 = 86,    // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_3 = 87,    // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_4 = 88,    // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_5 = 89,    // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_6 = 90,    // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_7 = 91,    // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_8 = 92,    // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_9 = 93,    // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_10 = 94,   // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_11 = 95,   // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_12 = 96,   // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_13 = 97,   // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_14 = 98,   // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_15 = 99,   // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_16 = 100,  // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_17 = 101,  // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_18 = 102,  // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_19 = 103,  // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_4_AF32_20 = 104,  // SDM120M readings as 32 bit float, for module 4
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_0 = 105,   // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_1 = 106,   // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_2 = 107,   // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_3 = 108,   // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_4 = 109,   // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_5 = 110,   // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_6 = 111,   // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_7 = 112,   // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_8 = 113,   // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_9 = 114,   // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_10 = 115,  // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_11 = 116,  // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_12 = 117,  // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_13 = 118,  // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_14 = 119,  // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_15 = 120,  // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_16 = 121,  // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_17 = 122,  // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_18 = 123,  // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_19 = 124,  // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_5_AF32_20 = 125,  // SDM120M readings as 32 bit float, for module 5
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_0 = 126,   // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_1 = 127,   // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_2 = 128,   // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_3 = 129,   // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_4 = 130,   // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_5 = 131,   // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_6 = 132,   // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_7 = 133,   // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_8 = 134,   // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_9 = 135,   // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_10 = 136,  // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_11 = 137,  // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_12 = 138,  // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_13 = 139,  // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_14 = 140,  // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_15 = 141,  // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_16 = 142,  // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_17 = 143,  // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_18 = 144,  // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_19 = 145,  // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_6_AF32_20 = 146,  // SDM120M readings as 32 bit float, for module 6
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_0 = 147,   // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_1 = 148,   // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_2 = 149,   // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_3 = 150,   // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_4 = 151,   // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_5 = 152,   // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_6 = 153,   // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_7 = 154,   // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_8 = 155,   // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_9 = 156,   // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_10 = 157,  // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_11 = 158,  // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_12 = 159,  // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_13 = 160,  // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_14 = 161,  // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_15 = 162,  // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_16 = 163,  // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_17 = 164,  // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_18 = 165,  // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_19 = 166,  // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_7_AF32_20 = 167,  // SDM120M readings as 32 bit float, for module 7
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_0 = 168,   // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_1 = 169,   // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_2 = 170,   // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_3 = 171,   // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_4 = 172,   // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_5 = 173,   // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_6 = 174,   // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_7 = 175,   // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_8 = 176,   // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_9 = 177,   // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_10 = 178,  // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_11 = 179,  // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_12 = 180,  // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_13 = 181,  // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_14 = 182,  // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_15 = 183,  // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_16 = 184,  // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_17 = 185,  // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_18 = 186,  // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_19 = 187,  // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_8_AF32_20 = 188,  // SDM120M readings as 32 bit float, for module 8
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_0 = 189,   // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_1 = 190,   // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_2 = 191,   // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_3 = 192,   // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_4 = 193,   // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_5 = 194,   // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_6 = 195,   // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_7 = 196,   // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_8 = 197,   // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_9 = 198,   // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_10 = 199,  // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_11 = 200,  // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_12 = 201,  // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_13 = 202,  // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_14 = 203,  // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_15 = 204,  // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_16 = 205,  // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_17 = 206,  // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_18 = 207,  // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_19 = 208,  // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_9_AF32_20 = 209,  // SDM120M readings as 32 bit float, for module 9
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_0 = 210,  // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_1 = 211,  // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_2 = 212,  // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_3 = 213,  // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_4 = 214,  // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_5 = 215,  // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_6 = 216,  // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_7 = 217,  // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_8 = 218,  // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_9 = 219,  // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_10 = 220, // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_11 = 221, // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_12 = 222, // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_13 = 223, // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_14 = 224, // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_15 = 225, // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_16 = 226, // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_17 = 227, // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_18 = 228, // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_19 = 229, // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_10_AF32_20 = 230, // SDM120M readings as 32 bit float, for module 10
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_0 = 231,  // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_1 = 232,  // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_2 = 233,  // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_3 = 234,  // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_4 = 235,  // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_5 = 236,  // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_6 = 237,  // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_7 = 238,  // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_8 = 239,  // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_9 = 240,  // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_10 = 241, // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_11 = 242, // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_12 = 243, // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_13 = 244, // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_14 = 245, // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_15 = 246, // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_16 = 247, // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_17 = 248, // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_18 = 249, // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_19 = 250, // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_11_AF32_20 = 251, // SDM120M readings as 32 bit float, for module 11
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_0 = 252,  // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_1 = 253,  // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_2 = 254,  // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_3 = 255,  // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_4 = 256,  // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_5 = 257,  // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_6 = 258,  // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_7 = 259,  // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_8 = 260,  // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_9 = 261,  // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_10 = 262, // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_11 = 263, // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_12 = 264, // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_13 = 265, // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_14 = 266, // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_15 = 267, // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_16 = 268, // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_17 = 269, // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_18 = 270, // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_19 = 271, // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_12_AF32_20 = 272, // SDM120M readings as 32 bit float, for module 12
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_0 = 273,  // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_1 = 274,  // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_2 = 275,  // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_3 = 276,  // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_4 = 277,  // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_5 = 278,  // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_6 = 279,  // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_7 = 280,  // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_8 = 281,  // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_9 = 282,  // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_10 = 283, // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_11 = 284, // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_12 = 285, // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_13 = 286, // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_14 = 287, // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_15 = 288, // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_16 = 289, // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_17 = 290, // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_18 = 291, // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_19 = 292, // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_13_AF32_20 = 293, // SDM120M readings as 32 bit float, for module 13
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_0 = 294,  // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_1 = 295,  // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_2 = 296,  // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_3 = 297,  // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_4 = 298,  // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_5 = 299,  // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_6 = 300,  // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_7 = 301,  // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_8 = 302,  // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_9 = 303,  // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_10 = 304, // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_11 = 305, // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_12 = 306, // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_13 = 307, // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_14 = 308, // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_15 = 309, // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_16 = 310, // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_17 = 311, // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_18 = 312, // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_19 = 313, // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_14_AF32_20 = 314, // SDM120M readings as 32 bit float, for module 14
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_0 = 315,  // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_1 = 316,  // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_2 = 317,  // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_3 = 318,  // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_4 = 319,  // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_5 = 320,  // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_6 = 321,  // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_7 = 322,  // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_8 = 323,  // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_9 = 324,  // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_10 = 325, // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_11 = 326, // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_12 = 327, // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_13 = 328, // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_14 = 329, // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_15 = 330, // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_16 = 331, // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_17 = 332, // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_18 = 333, // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_19 = 334, // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_15_AF32_20 = 335, // SDM120M readings as 32 bit float, for module 15
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_0 = 336,  // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_1 = 337,  // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_2 = 338,  // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_3 = 339,  // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_4 = 340,  // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_5 = 341,  // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_6 = 342,  // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_7 = 343,  // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_8 = 344,  // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_9 = 345,  // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_10 = 346, // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_11 = 347, // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_12 = 348, // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_13 = 349, // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_14 = 350, // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_15 = 351, // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_16 = 352, // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_17 = 353, // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_18 = 354, // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_19 = 355, // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_16_AF32_20 = 356, // SDM120M readings as 32 bit float, for module 16
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_0 = 357,  // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_1 = 358,  // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_2 = 359,  // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_3 = 360,  // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_4 = 361,  // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_5 = 362,  // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_6 = 363,  // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_7 = 364,  // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_8 = 365,  // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_9 = 366,  // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_10 = 367, // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_11 = 368, // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_12 = 369, // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_13 = 370, // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_14 = 371, // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_15 = 372, // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_16 = 373, // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_17 = 374, // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_18 = 375, // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_19 = 376, // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_17_AF32_20 = 377, // SDM120M readings as 32 bit float, for module 17
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_0 = 378,  // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_1 = 379,  // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_2 = 380,  // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_3 = 381,  // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_4 = 382,  // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_5 = 383,  // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_6 = 384,  // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_7 = 385,  // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_8 = 386,  // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_9 = 387,  // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_10 = 388, // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_11 = 389, // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_12 = 390, // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_13 = 391, // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_14 = 392, // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_15 = 393, // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_16 = 394, // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_17 = 395, // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_18 = 396, // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_19 = 397, // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_18_AF32_20 = 398, // SDM120M readings as 32 bit float, for module 18
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_0 = 399,  // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_1 = 400,  // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_2 = 401,  // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_3 = 402,  // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_4 = 403,  // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_5 = 404,  // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_6 = 405,  // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_7 = 406,  // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_8 = 407,  // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_9 = 408,  // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_10 = 409, // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_11 = 410, // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_12 = 411, // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_13 = 412, // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_14 = 413, // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_15 = 414, // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_16 = 415, // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_17 = 416, // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_18 = 417, // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_19 = 418, // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_19_AF32_20 = 419, // SDM120M readings as 32 bit float, for module 19
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_0 = 420,  // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_1 = 421,  // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_2 = 422,  // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_3 = 423,  // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_4 = 424,  // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_5 = 425,  // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_6 = 426,  // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_7 = 427,  // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_8 = 428,  // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_9 = 429,  // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_10 = 430, // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_11 = 431, // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_12 = 432, // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_13 = 433, // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_14 = 434, // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_15 = 435, // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_16 = 436, // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_17 = 437, // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_18 = 438, // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_19 = 439, // SDM120M readings as 32 bit float, for module 20
    RTDB_MBCM_X_SDM120MREADINGS_20_AF32_20 = 440, // SDM120M readings as 32 bit float, for module 20
    NUM_OF_tF32S = 441
} tF32SEnumT;

typedef enum
{
    SIGNAL_ERROR = 0x00,         ///< Value unreliable
    SIGNAL_MISSING = 0x0F,       ///< Value missing
    SIGNAL_CAN_TIMEOUT = 0x3F,   ///< Timeout on CAN signal
    SIGNAL_OK = 0xFF             ///< Value reliable, use value
} signalStateT;

typedef enum
{
    OBJECT_STANDARD = 0,    ///< Value is derived from program
    OBJECT_OVERRIDDEN = 1,  ///< Value is derived from external source
    OBJECT_NOT_INIT = 255,
} objectStatusT;

typedef struct
{
    tU32 crc32;                         ///< CRC of all object's variables
    signalStateT signalState : 8;       ///< state of the signal, i.e., its reliability
    objectStatusT objectStatus : 8;     ///< status of this object
    tU8 signalUnit;                     ///< unit of the signal, i.e., volt or RPM
    const char* signalCmnt;             ///< Signal comment
} rtdbT;

typedef struct
{
    rtdbT ss;
    tS8 tS8_val;
    tS8 tS8_min;
    tS8 tS8_def;
    tS8 tS8_max;
} tS8S;

typedef struct
{
    rtdbT ss;
    tS16 tS16_val;
    tS16 tS16_min;
    tS16 tS16_def;
    tS16 tS16_max;
} tS16S;

typedef struct
{
    rtdbT ss;
    tS32 tS32_val;
    tS32 tS32_min;
    tS32 tS32_def;
    tS32 tS32_max;
} tS32S;

typedef struct
{
    rtdbT ss;
    tU8 tU8_val;
    tU8 tU8_min;
    tU8 tU8_def;
    tU8 tU8_max;
} tU8S;

typedef struct
{
    rtdbT ss;
    tU16 tU16_val;
    tU16 tU16_min;
    tU16 tU16_def;
    tU16 tU16_max;
} tU16S;

typedef struct
{
    rtdbT ss;
    tU32 tU32_val;
    tU32 tU32_min;
    tU32 tU32_def;
    tU32 tU32_max;
} tU32S;

typedef struct
{
    rtdbT ss;
    tF32 tF32_val;
    tF32 tF32_min;
    tF32 tF32_def;
    tF32 tF32_max;
} tF32S;

typedef struct
{
    rtdbT ss;
    tU8 tB_val;
    tU8 tB_min;
    tU8 tB_def;
    tU8 tB_max;
} tBS;

typedef struct
{
    rtdbT ss;
    tU32 tE_val;
    tU32 tE_min;
    tU32 tE_def;
    tU32 tE_max;
} tES;

#endif
